### ISSUE TITLE
 'camera_id' and 'show_fps' error

### ISSUE THREAD

**Issue by knock12neha** [untoms/FinalProject_D3TI_UNS#1]
hey i need a help i am not able to run your code either in eclipse or in android studio.
it is being imported in android studio but it show two errors:
No resource identifier found for attribute 'camera_id' in package
No resource identifier found for attribute 'show_fps' in package
           it will be  very helpful if u can resolve my issue. waiting for your as soon as possible response.
Thanks and Regards

**Comment by untoms** [comment]
Open this app using aclipse and install C/C++ library in eclipse. You also need NDK library and OpenCV library and set path to those lib.
